badminton_wrapped:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: '/Users/c16305a/Documents/ECS/Sandpit/badminton-wrapped/data/badminton_wrapped.duckdb'
      threads: 1
      settings:
        preserve_insertion_order: false
        memory_limit: '8GB'
